import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import vm from "node:vm";

// assets/skill-tree.js is a plain browser script; run it against a page that has no trees.
const { WikiSkillTree } = (() => {
  const window = {};
  const document = { readyState: "complete", querySelectorAll: () => [], addEventListener() {}, documentElement: { getAttribute: () => null } };
  vm.runInContext(fs.readFileSync("assets/skill-tree.js", "utf8"), vm.createContext({ window, document }));
  return window;
})();

const { sanitize, resolveText, resolveView } = WikiSkillTree;

test("the sanitizer gives the same results as tools/wiki_util.py", () => {
  const cases = JSON.parse(fs.readFileSync("tools/testdata/sanitize_cases.json", "utf8"));
  for (const c of cases) assert.equal(sanitize(c.input), c.display, c.name);
});

// A skill whose damage line has three tiers (group 1), a standalone line (group 0), a sentence a tier
// can erase (group 2: the empty tier outranks the text) and a view reduction.
const model = {
  baseUseView: 10000,
  lines: [
    { node: 0, serialNo: 1, group: 1, prio: 0, order: 1, type: "text" },
    { node: 11, serialNo: 2, group: 1, prio: 1, order: 1, type: "text" },
    { node: 12, serialNo: 3, group: 1, prio: 2, order: 1, type: "text" },
    { node: 0, serialNo: 4, group: 0, prio: 0, order: 4, type: "text" },
    { node: 0, serialNo: 5, group: 2, prio: 0, order: 5, type: "text" },
    { node: 13, serialNo: 6, group: 2, prio: 1, order: 5, type: "text" },
    { node: 11, serialNo: 7, group: 0, prio: 0, type: "view", viewDelta: -500 },
    { node: 12, serialNo: 8, group: 0, prio: 0, type: "view", viewDelta: -1000 },
  ],
};
const lang = { base: "Hit.", lt: ["<br>60%.", "<br>70%.", "<br>80%.", "<br>Passive.", "<br>Self only.", "", "", ""] };
const resolve = (...nodes) => resolveText(model, lang, new Set(nodes));

test("only the highest unlocked tier of a group is printed, in the slot the group starts", () => {
  assert.equal(resolve(), "Hit.<br>60%.<br>Passive.<br>Self only.");
  assert.equal(resolve(11), "Hit.<br>70%.<br>Passive.<br>Self only.");
  assert.equal(resolve(11, 12), "Hit.<br>80%.<br>Passive.<br>Self only.");
});

test("an unlocked tier with no text erases its sentence", () => {
  assert.equal(resolve(13), "Hit.<br>60%.<br>Passive.");
});

test("a tier listed twice is printed once", () => {
  const twice = { base: "", lt: ["A", "B", "B", "", "", "", "", ""] };
  assert.equal(resolveText(model, twice, new Set([11, 12])), "B");
});

test("view cost is additive over the unlocked nodes", () => {
  assert.equal(resolveView(model, new Set()), 10000);
  assert.equal(resolveView(model, new Set([11])), 9500);
  assert.equal(resolveView(model, new Set([11, 12])), 8500);
});

test("every bloom skill in every language reproduces the maxed text the generator printed", (t) => {
  const file = "_data/wiki/SkillUpgradeModel.json";
  if (!fs.existsSync(file)) return t.skip(`${file} is generated by tools/gen_skill_upgrade_model.py`);
  const all = JSON.parse(fs.readFileSync(file, "utf8"));
  let checked = 0;
  for (const hero of Object.values(all)) {
    for (const skill of hero.skills) {
      const active = new Set(Object.keys(skill.tree).map(Number));
      assert.equal(resolveView(skill, active), skill.maxedView, `view of ${skill.skillId}`);
      for (const [code, L] of Object.entries(skill.langs)) {
        assert.equal(resolveText(skill, L, active), L.maxed, `${skill.skillId} in ${code}`);
        checked++;
      }
    }
  }
  assert.ok(checked > 0);
});
