// Copies the generated skill index JSON from the repo's /api dir into
// search/public/api so Vite serves it locally during dev/build.
// Source of truth stays in /api (generated by tools/generate_skill_search_index.py);
// these copies are gitignored and may go stale — re-run `pnpm sync-index`.
import { copyFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoApi = resolve(here, '..', '..', 'api')
const destDir = resolve(here, '..', 'public', 'api')

const files = ['skill-index.json', 'skill-index-version.json']

mkdirSync(destDir, { recursive: true })
for (const f of files) {
  const src = resolve(repoApi, f)
  if (!existsSync(src)) {
    console.error(`[sync-index] missing source: ${src}`)
    process.exitCode = 1
    continue
  }
  copyFileSync(src, resolve(destDir, f))
  console.log(`[sync-index] copied ${f}`)
}
